pipeline {
    agent any
    options {
        timeout(time: 15, unit: 'SECONDS')
    }
    stages {
        stage('Cleaning') {
            steps {
                mvn clean
            }
        }
        stage('Compiling') {
            steps {
                mvn compile
            }
        }
        stage('Installing') {
            steps {
                mvn install
            }
        }
    }
}