pipeline {
    agent any
    options {
        timeout(time: 15, unit: 'SECONDS')
    }
    stages {
        stage('Reading parameters') {
            steps {
                echo BRANCH_NAME
            }
        }
    }
}