--CREATE TABLE PERSON (
--    ID UUID PRIMARY KEY,
--    NAME VARCHAR(255) NOT NULL,
--    LAST_NAME VARCHAR(255) NOT NULL,
--    FULL_NAME VARCHAR(255) NOT NULL,
--    BIRTHDATE DATE
--);

CREATE TABLE MANAGEMENT_USER (
    ID UUID PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    ENCRYPTED_PASSWORD VARCHAR(255) NOT NULL,
    IS_ENABLED BOOLEAN NOT NULL,
    IS_ACCOUNT_NON_EXPIRED BOOLEAN NOT NULL,
    IS_CREDENTIALS_NON_EXPIRED BOOLEAN NOT NULL,
    IS_ACCOUNT_NON_LOCKED BOOLEAN NOT NULL
--    PERSON_ID INTEGER REFERENCES PERSON(ID) NOT NULL
);

CREATE TABLE MANAGEMENT_ROLE (
    ID UUID PRIMARY KEY,
    ROLE_NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE MANAGEMENT_USER_ROLE (
    MANAGEMENT_USER_ID UUID REFERENCES MANAGEMENT_USER(ID),
    MANAGEMENT_ROLE_ID UUID REFERENCES MANAGEMENT_ROLE(ID)
);